const PRIORITY_META = {
	P0: { emoji: '🔴', label: 'Critical — broken' },
	P1: { emoji: '🟠', label: 'High priority' },
	P2: { emoji: '🟡', label: 'Opportunities' },
};
const PRIORITY_ORDER = ['P0', 'P1', 'P2'];
const CATEGORY_LABEL = {
	'technical-seo': 'Technical SEO',
	aeo: 'AEO (answer engines)',
	'content-gap': 'Content gaps',
};

const DATA_COMMENT_RE = /<!-- seo-scan-data: (.*?) -->/s;

export function parsePreviousData(issueBody) {
	if (!issueBody) return null;
	const match = issueBody.match(DATA_COMMENT_RE);
	if (!match) return null;
	try {
		return JSON.parse(match[1]);
	} catch {
		return null;
	}
}

function renderFinding(f) {
	const scope = f.page ? `\`${f.page}\`` : 'sitewide';
	const lines = [`- [ ] **${f.title}** — ${scope} (${f.siteLabel})`, `  ${f.detail}`];
	if (f.fix) lines.push(`  *Fix:* ${f.fix}`);
	return lines.join('\n');
}

export function buildReport({ findings, previousData, scannedAt, siteSummaries }) {
	const counts = { P0: 0, P1: 0, P2: 0 };
	for (const f of findings) counts[f.priority]++;

	const currentIds = new Set(findings.map((f) => f.id));
	const previousIds = new Set((previousData?.items ?? []).map((i) => i.id));
	const newItems = findings.filter((f) => !previousIds.has(f.id));
	const resolvedItems = (previousData?.items ?? []).filter((i) => !currentIds.has(i.id));

	const lines = [];
	lines.push(`# Weekly SEO & AEO Scan — ${scannedAt}`);
	lines.push('');
	lines.push(
		`**${findings.length} open item(s)** across ${siteSummaries.map((s) => `${s.pageCount} page(s) on ${s.label}`).join(', ')}: ` +
			`${counts.P0} critical, ${counts.P1} high priority, ${counts.P2} opportunities.`
	);
	lines.push('');
	lines.push('Check items off as you handle them — this issue gets its body replaced each week with the current list, so a checked box just means "done as of last week\'s read"; re-open anything that resurfaces.');

	for (const priority of PRIORITY_ORDER) {
		const items = findings.filter((f) => f.priority === priority);
		if (items.length === 0) continue;
		lines.push('');
		lines.push(`## ${PRIORITY_META[priority].emoji} ${PRIORITY_META[priority].label} (${items.length})`);

		const byCategory = new Map();
		for (const f of items) byCategory.set(f.category, [...(byCategory.get(f.category) ?? []), f]);
		for (const [category, catItems] of byCategory) {
			lines.push('');
			lines.push(`### ${CATEGORY_LABEL[category] ?? category}`);
			for (const f of catItems) lines.push(renderFinding(f));
		}
	}

	if (findings.length === 0) {
		lines.push('');
		lines.push('Nothing open. Clean scan.');
	}

	if (newItems.length > 0 || resolvedItems.length > 0) {
		lines.push('');
		lines.push('## Since last scan');
		if (newItems.length > 0) {
			lines.push('');
			lines.push(`**🆕 New (${newItems.length}):**`);
			for (const f of newItems) lines.push(`- ${PRIORITY_META[f.priority].emoji} ${f.title} — ${f.page ? `\`${f.page}\`` : 'sitewide'} (${f.siteLabel})`);
		}
		if (resolvedItems.length > 0) {
			lines.push('');
			lines.push(`**✅ Resolved since last week (${resolvedItems.length}):**`);
			for (const i of resolvedItems) lines.push(`- ${i.title} — ${i.page ? `\`${i.page}\`` : 'sitewide'} (${i.siteLabel ?? ''})`);
		}
	} else if (previousData) {
		lines.push('');
		lines.push('## Since last scan');
		lines.push('No change in open items.');
	}

	lines.push('');
	lines.push('---');
	lines.push(
		'_Generated by `scripts/seo-scan/`. Tune thresholds and target topics in `scripts/seo-scan/config.mjs`. ' +
			'This issue is reused week to week — the body always reflects the latest scan._'
	);

	const dataPayload = {
		scannedAt,
		items: findings.map((f) => ({ id: f.id, priority: f.priority, title: f.title, page: f.page, siteLabel: f.siteLabel })),
	};
	lines.push('');
	lines.push(`<!-- seo-scan-data: ${JSON.stringify(dataPayload)} -->`);

	return {
		markdown: lines.join('\n'),
		counts,
		newCount: newItems.length,
		resolvedCount: resolvedItems.length,
	};
}
